FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
	build-essential \
	poppler-utils \
	tesseract-ocr \
	&& rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -m spacy download en_core_web_sm

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]